includes:
  - base.yaml
model:
  model_name: GDGMTvGIN #
ood:
  # ood_alg: BrainOOD
  ood_param: 0.0    # info loss coefficient
  trade_off: 0.5    # trade-off coefficient
  diffusion_trade_off: 0.5
  entropy_trade_off: 0.01
  feature_dropout: 0.5
  temperature: 0.08
  variance_weight: 0.5
  covariance_weight: 0.02
  extra_param:
    - "bern"    # sampling method
    - 20      # decay_interval
    - 0.7     # final_r
    - 5    # sample_rounds
train:
  max_epoch: 20
  pre_epoch: 50
  pretrain_bs: 32
  lr: 2e-3
  pre_lr: 5e-4
  ball_r: 0.25
  orig_edge_drop: 0.05
  coarse_edge_drop: 0.20
  orig_feature_mask: 0.05
  coarse_feature_mask: 0.20
  orig_noise_std: 0.01
  coarse_noise_std: 0.03

